### ISSUE TITLE
Windows CI fails to find Java for python-biofromats

### ISSUE THREAD

**Issue by yfukai** [yfukai/pycziutils#2]
In the Github Actions CI workflow, installation to Windows environments fails with the following error.
Adding  `actions / setup-java` did not help to solve this issue.
Maybe it is necessary to add the PATH for java, but no clue for now...

```
EnvCommandError

  Command C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\pycziutils-MFzUGVGp-py3.7\Scripts\pip.exe install --no-deps C:\Users\runneradmin\AppData\Local\pypoetry\Cache\artifacts\a3\45\4f\446de025b933d9739f17e88d212ff74232b3507b704dc80f449f6ddd85\python-javabridge-4.0.3.tar.gz errored with the following return code 1, and output: 
  Processing c:\users\runneradmin\appdata\local\pypoetry\cache\artifacts\a3\45\4f\446de025b933d9739f17e88d212ff74232b3507b704dc80f449f6ddd85\python-javabridge-4.0.3.tar.gz
      ERROR: Command errored out with exit status 1:

       command: 'C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\pycziutils-MFzUGVGp-py3.7\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-req-build-ijlrewbz\\setup.py'"'"'; __file__='"'"'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-req-build-ijlrewbz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\RUNNER~1\AppData\Local\Temp\pip-pip-egg-info-nxgmqeq1'
           cwd: C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-ijlrewbz\
      Complete output (9 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-ijlrewbz\setup.py", line 412, in <module>
          ext_modules=ext_modules(),
        File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-ijlrewbz\setup.py", line 99, in ext_modules
          jdk_home = find_jdk()
        File "C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-ijlrewbz\javabridge\locate.py", line 223, in find_jdk
          "Failed to find the Java Development Kit. "
      RuntimeError: Failed to find the Java Development Kit. Please download and install the Oracle JDK 1.6 or later
      ----------------------------------------
```

**Comment by yfukai** [comment]
Solved by PR #6 .
